apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-test-backstage
  namespace: holaluz
  title: API Test Backstage
  description: awesome documentation for api in backstage
  tags:
    - kotlin
    - openapi
  links:
    - url: https://dashboard.example.com
      title: Website
      icon: dashboard
  annotations:
    github.com/project-slug: kanekoticTestOrg/test-backstage
    backstage.io/techdocs-ref: dir:.
    backstage.io/adr-location: docs/adrs
    kafka.apache.org/consumer-groups: cluster-name/consumer-group-name
spec:
  type: openapi
  lifecycle: experimental
  owner: group:kanekotic
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json
