apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-backstage
  description: awesome documentation for backstage
  annotations:
    github.com/project-slug: kanekoticTestOrg/test-backstage
    backstage.io/techdocs-ref: dir:.
    backstage.io/adr-location: docs/adrs
    kafka.apache.org/consumer-groups: awesome-consumer-group
  links:
    - url: https://dashboard.example.com
      title: Website
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: group:pet-managers
  providesApis:
    - petstore
    - internal/streetlights
    - hello-world
