apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-backstage
  description: An example of a Backstage application.
  annotations:
    backstage.io/adr-location: docs/adrs
  annotations:
    github.com/project-slug: kanekoticTestOrg/test-backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
