---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: user-management
  description: a domain
  tags:
  - domain
spec:
  owner: user-management-team
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: user-management-team
  description: a test group
spec:
  type: team
  profile:
    displayName: user management team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: user-management
  description: Some system
  tags:
    - system
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: user-management-team
  domain: user-management
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-management-service
  description: a component
  tags:
  - springboot
spec:
  owner: user-management-team
  lifecycle: production
  partOf: domain:user-management
  providesApis:
    - componentA-api
  system: user-management
  dependsOn: []
  consumesApis: []
  type: service
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: user-management-api
  description: the API
spec:
  system: user-management
  type: openapi
  lifecycle: production
  owner: user-management-team
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  system: user-management
  name: my-db
  description: some db
  tags:
    - mysql
spec:
  type: database
  lifecycle: production
  owner: user-management-team
  dependencyOf: component:user-management-service